# Konfiguracja skanera Qodana
version: "1.0"

# Określenie profilu (zestawu reguł sprawdzających kod)
profile:
  name: qodana.recommended

# Wykluczenie folderów, których nie chcemy skanować (np. testy lub biblioteki)
exclude:
  - name: All
    paths:
      - Backend.Tests/*

# Opcjonalne: ustawienie progu błędów, powyżej którego proces ma "upaść" (fail)
failThreshold: 0